spring.application.name="BTS Task"

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bts}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret="${APP_JWT_SECRET:igfDv1sKHrc206haC3P3la32iQBZYu32LMrzp9G3bhw=}"
# 30 Minutes
app.jwt.accessTokenTtl=PT30M
# 7 Days
app.jwt.refreshTokenTtl=P7D
